### ISSUE TITLE
this.context = Script.createContext();                         ^ TypeError: undefined is not a function

### ISSUE THREAD

**Issue by erjoalgo** [swank-js/swank-js#77]
```
myuser-netbook$npm run swank

> swank-js@0.0.5 swank /home/myuser/programs/swank-js-master
> node ./swank.js

/home/myuser/programs/swank-js-master/swank-handler.js:303
  this.context = Script.createContext();
                        ^
TypeError: undefined is not a function
    at new DefaultRemote (/home/myuser/programs/swank-js-master/swank-handler.js:303:25)
    at new Executive (/home/myuser/programs/swank-js-master/swank-handler.js:370:21)
    at Object.<anonymous> (/home/myuser/programs/swank-js-master/swank.js:43:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "swank"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! swank-js@0.0.5 swank: `node ./swank.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swank-js@0.0.5 swank script 'node ./swank.js'.
npm ERR! This is most likely a problem with the swank-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./swank.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls swank-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/myuser/programs/swank-js-master/npm-debug.log
```

**Comment by erjoalgo** [comment]
I solved this issue by using 
```
    //this.context = Script.createContext(); does not work, Script.createContext undefined
    this.context = vm.createContext();
```

**Comment by jayknowstheway** [comment]
I get the same error with that code, erjoalgo, except this time it's vm that's not defined.. could it be a bug somewhere else?

**Comment by erjoalgo** [comment]
On line 31 of swank-handler.js, I have a line 

    var vm = require('vm'), Script = vm.Script;

Do you have that line? What version of swank-js do you have? I believe I downloaded the latest version from the zip file.

```
$npm -v swank-js
2.10.1
```

**Comment by jayknowstheway** [comment]
Hello and thanks for the quick reply! Yes, I had noticed that line, but still, I got the error message, which made me think maybe there was a bug somewhere. I'll keep looking through the code..

**Comment by baerrach** [comment]
This still happens with node@4.2.4, script@0.1.4 and swank@0.0.5
    this.context = vm.createContext();
fixed it for me.
