### ISSUE TITLE
TypeError: Script.createContext is not a function

### ISSUE THREAD

**Issue by anquegi** [swank-js/swank-js#86]
Hi Thanks for this project, I'm learning node, and usually use emacs, I did the setup and follow this tutorial: 

[TUTORIAL](http://shapeshed.com/creating-a-basic-site-with-node-and-express/)

then I add this to the project.json:

╭─anquegi@localhost  ~/src/node/express_example ‹ruby-2.2.3@learn-dev› 
╰─$ cat package.json 
{
  "name": "express_example",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0",
    "stylus": "0.42.3"
  },
  "devDependencies": {
     "swank-js": ">=0.0.1"
  },
  "scripts": {
      "swank": "node node_modules/swank-js"
  }
}

before the section git I tried the project, 
╭─anquegi@localhost  ~/src/node/express_example ‹ruby-2.2.3@learn-dev› 
╰─$ npm start

> express_example@0.0.0 start /home/anquegi/src/node/express_example
> node ./bin/www

GET / 200 309.201 ms - 170
GET /stylesheets/style.css 200 133.805 ms - 110
GET /favicon.ico 404 38.383 ms - 1195
GET /favicon.ico 404 30.697 ms - 1195

then I tried the swank I get this error:

╭─anquegi@localhost  ~/src/node/express_example ‹ruby-2.2.3@learn-dev› 
╰─$ npm run swank

> express_example@0.0.0 swank /home/anquegi/src/node/express_example
> node node_modules/swank-js

/home/anquegi/src/node/express_example/node_modules/swank-js/swank-handler.js:290
  this.context = Script.createContext();
                        ^

TypeError: Script.createContext is not a function
    at new DefaultRemote (/home/anquegi/src/node/express_example/node_modules/swank-js/swank-handler.js:290:25)
    at new Executive (/home/anquegi/src/node/express_example/node_modules/swank-js/swank-handler.js:349:21)
    at Object.<anonymous> (/home/anquegi/src/node/express_example/node_modules/swank-js/swank.js:43:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Linux 4.3.3-303.fc23.x86_64
npm ERR! argv "/home/anquegi/bin/node-v5.5.0-linux-x64/bin/node" "/home/anquegi/bin/node-v5.5.0-linux-x64/bin/npm" "run" "swank"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! express_example@0.0.0 swank: `node node_modules/swank-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the express_example@0.0.0 swank script 'node node_modules/swank-js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the express_example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/swank-js
npm ERR! You can get their info via:
npm ERR!     npm owner ls express_example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anquegi/src/node/express_example/npm-debug.log

the content of the npm-debug.log is:

╭─anquegi@localhost  ~/src/node/express_example ‹ruby-2.2.3@learn-dev› 
╰─$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/home/anquegi/bin/node-v5.5.0-linux-x64/bin/node',
1 verbose cli   '/home/anquegi/bin/node-v5.5.0-linux-x64/bin/npm',
1 verbose cli   'run',
1 verbose cli   'swank' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'preswank', 'swank', 'postswank' ]
5 info lifecycle express_example@0.0.0~preswank: express_example@0.0.0
6 silly lifecycle express_example@0.0.0~preswank: no script for preswank, continuing
7 info lifecycle express_example@0.0.0~swank: express_example@0.0.0
8 verbose lifecycle express_example@0.0.0~swank: unsafe-perm in lifecycle true
9 verbose lifecycle express_example@0.0.0~swank: PATH: /home/anquegi/bin/node-v5.5.0-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/home/anquegi/src/node/express_example/node_modules/.bin:/home/anquegi/.rvm/gems/ruby-2.2.3@learn-dev/bin:/home/anquegi/.rvm/gems/ruby-2.2.3@global/bin:/home/anquegi/.rvm/rubies/ruby-2.2.3/bin:/home/anquegi/bin/node-v5.5.0-linux-x64/bin:/home/anquegi/bin:/home/anquegi/.roswell/bin:/home/anquegi/.cabal/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/anquegi/.local/bin:/home/anquegi/bin:/home/anquegi/.rvm/bin
10 verbose lifecycle express_example@0.0.0~swank: CWD: /home/anquegi/src/node/express_example
11 silly lifecycle express_example@0.0.0~swank: Args: [ '-c', 'node node_modules/swank-js' ]
12 silly lifecycle express_example@0.0.0~swank: Returned: code: 1  signal: null
13 info lifecycle express_example@0.0.0~swank: Failed to exec swank script
14 verbose stack Error: express_example@0.0.0 swank: `node node_modules/swank-js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/anquegi/bin/node-v5.5.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/anquegi/bin/node-v5.5.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid express_example@0.0.0
16 verbose cwd /home/anquegi/src/node/express_example
17 error Linux 4.3.3-303.fc23.x86_64
18 error argv "/home/anquegi/bin/node-v5.5.0-linux-x64/bin/node" "/home/anquegi/bin/node-v5.5.0-linux-x64/bin/npm" "run" "swank"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error express_example@0.0.0 swank: `node node_modules/swank-js`
22 error Exit status 1
23 error Failed at the express_example@0.0.0 swank script 'node node_modules/swank-js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the express_example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/swank-js
23 error You can get their info via:
23 error     npm owner ls express_example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks for yout help

**Comment by MC-Escherichia** [comment]
This has to do with updates to Node's Script API. I have fixed it in my fork, but it hasn't been merged into the main project yet. You can use my fork by following the steps

```
git clone http//github.com/MC-Escherichia/swank-js.git
cd swank-js 
npm link 
```

then go to your project  and run

```
 npm link swank-js 
```

I am hoping that the maintainers hand off this awesome project at some point in the future, but for now we have to work around like this.

**Comment by anquegi** [comment]
Thanks, It is working like a charm. even with company. Happy to continue learning javascript and company.

**Comment by ncouture** [comment]
@MC-Escherichia thank you for staying on top of this!

**Comment by peey** [comment]
I was facing the same issue.

I found that this was fixed in https://github.com/swank-js/swank-js/issues/80, but it seems like it hasn't been updated on npm yet so in order to fetch the latest version you'll have to install it directly via github by using

```
npm install -g swank-js/swank-js
```

Please verify if this works so that we may close this issue

**Comment by cmal** [comment]
I've encountered with the same problem.  @peey I used `npm install -g swank-js/swank-js`, and the problem solved.
