### ISSUE TITLE
npm run swank errors

### ISSUE THREAD

**Issue by gustad** [swank-js/swank-js#89]
npm run swank errors

This is my first attempt at getting swank-js running and I'm getting this error:

```
$ npm run swank

> @ swank /home/zed
> node node_modules/swank-js

/home/zed/node_modules/swank-js/swank-handler.js:290
  this.context = Script.createContext();
                        ^

TypeError: Script.createContext is not a function
    at new DefaultRemote (/home/zed/node_modules/swank-js/swank-handler.js:290:25)
    at new Executive (/home/zed/node_modules/swank-js/swank-handler.js:349:21)
    at Object.<anonymous> (/home/zed/node_modules/swank-js/swank.js:43:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

Is this a user error, or is the swank-js not compatible with my version of node (v6.9.4)?

**Comment by Crinklewott** [comment]
A stop-gap fix for this seems to be in Issue #77, but yeah... I'm also getting this,

**Comment by anoduck** [comment]
Apparently, this still exists.
